# Generated by Django 4.2.16 on 2025-09-30 07:17

from django.db import migrations


def create_leaderboard_view(apps, schema_editor):
    """Create optimized leaderboard view."""
    schema_editor.execute("""
        CREATE VIEW IF NOT EXISTS leaderboard_view AS
        SELECT
            gs.id as game_id,
            p.id as player_id,
            p.username,
            gs.score,
            gs.level_reached,
            gs.duration_seconds,
            gs.completed_at,
            gs.ghosts_eaten,
            gs.dots_collected,
            RANK() OVER (ORDER BY gs.score DESC, gs.completed_at ASC) as rank
        FROM game_sessions gs
        INNER JOIN players p ON gs.player_id = p.id
        ORDER BY gs.score DESC, gs.completed_at ASC;
    """)


def drop_leaderboard_view(apps, schema_editor):
    """Drop leaderboard view."""
    schema_editor.execute("DROP VIEW IF EXISTS leaderboard_view;")


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_leaderboard_view, drop_leaderboard_view),
    ]
