# Generated by Django 4.2.16 on 2025-09-30 07:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, help_text='Total score achieved in this game session', validators=[django.core.validators.MinValueValidator(0)])),
                ('level_reached', models.IntegerField(default=1, help_text='Highest level reached in this game session', validators=[django.core.validators.MinValueValidator(1)])),
                ('duration_seconds', models.IntegerField(default=0, help_text='Duration of the game session in seconds', validators=[django.core.validators.MinValueValidator(0)])),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the game session was completed')),
                ('lives_remaining', models.IntegerField(default=0, help_text='Number of lives remaining when game ended', validators=[django.core.validators.MinValueValidator(0)])),
                ('dots_collected', models.IntegerField(default=0, help_text='Total dots collected during the session', validators=[django.core.validators.MinValueValidator(0)])),
                ('ghosts_eaten', models.IntegerField(default=0, help_text='Total ghosts eaten during the session', validators=[django.core.validators.MinValueValidator(0)])),
                ('player', models.ForeignKey(help_text='Player who played this game session', on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Game Session',
                'verbose_name_plural': 'Game Sessions',
                'db_table': 'game_sessions',
                'ordering': ['-completed_at'],
                'indexes': [models.Index(fields=['-score', 'completed_at'], name='game_sessio_score_f63238_idx'), models.Index(fields=['player', '-completed_at'], name='game_sessio_player__f495c6_idx')],
            },
        ),
    ]
